spring.application.name=order-ms

server.port=9094

#spring.cloud.discovery.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#MongoDB application Property
spring.data.mongodb.uri=mongodb://localhost:27017/orderDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=orderDB


user.service.url=http://USER_INFORMATION/user

eureka.client.rest-template-timeout.eureka-connect-timeout=5000
eureka.client.rest-template-timeout.eureka-read-timeout=5000
spring.cloud.loadbalancer.ribbon.enabled=false

spring.cloud.loadbalancer.eager-load.clients=restaurant-service,user-information
eureka.client.webclient.enabled=false
eureka.client.rest-client.enabled=false